name = "sunwell"
version = "1.0.0"

description = "A Gleam package to encode & decode Hearthstone deckstrings."
licences = ["MIT"]
repository = { type = "github", user = "hugolgs-dev", repo = "sunwell" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
